config/routes.rb
Rails.application.routes.draw do
  get 'payments/index'
  post 'payments/create'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  root 'simple_pages#landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments
  validates :name, presence: true

  def self.search (search_term)
    if Rails.env.development?
      Product.where("name LIKE ?", "%#{search_term}%")
    elsif Rails.env.production?
      Product.where("name ilike ?", "%#{search_term}%")
    end
  end

  def average_rating
    comments.average(:rating).to_f
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def views
    #$redis.get("product:#{id}")
  end

  def viewed!
    #$redis.incr("product:#{id}")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], per_page: 10)
    @product.viewed!
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h2>Add a review:</h2>
  <%= form_for([@product,@product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <div class="rating"></div>
    </p>
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="carousel-item <%= "active" if product == @products.first %>">
  <%= image_tag(product.image_url, class: "img-fluid") %>
  <div class="carousel-caption d-none d-md-block" id="carouselBlock">
    <% cache @product do %>
      <h2><%= product.name %></h2>
      <p><%= product.description %></p>
      <p>$ <%= product.price %></p>
    <% end %>
  </div> <!--caption-->
</div> <!--item-->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render partial: 'form', product: @products %>

<%= link_to 'Show', @products %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<% cache (cache_key_for_products) do %>
  <table>
    <div class="container-fluid">
      <div class=row>
          <% @products.each do |product| %>
          <div class= "col-md-4 col-xs-12" id="items">
            <%= image_tag(product.image_url, class: "img-fluid") %>
            <h2><%= product.name %></h2>
            <p><%= product.description %></p>
            <p><%= product.color %></p>
            <p><%= product.price %></p>
            <span><%= link_to 'Show', product %></span>
            <%if signed_in? && current_user.admin?%>
              <span><%= link_to 'Edit', edit_product_path(product) %></span>
              <span><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></span>
            <%end%>
          </div> <!--column-->
          <% end %>
      </div> <!--row-->
    </div> <!--container-->
  </table>
<% end %>
<div class="learn">
  <%= link_to "Learn More", simple_pages_about_url%>
</div> <!--learn more-->

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render partial: 'form', product: @products %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @product do %>

  <div class=showing data-product-id="<%= @product.id %>">

    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Image url:</strong>
      <%= image_tag(@product.image_url, height: "350", width: "400", class: "img-zoom", data_zoom_image: "@product.image_url") %>
    </p>

    <p>
      <strong>Color:</strong>
      <%= @product.color %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @product.price %>
    </p>

    <p>
      <strong>Site Views:</strong>
      <%= @product.views %>
    </p>

    <p>
      Average Rating: <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>">
      </div>
    </p>
  </div>
<% end %>

<%= form_with(url: '/payments/create') do |form| %>
  <%= hidden_field_tag(:product_id, @product.id) %>
  <%= render partial: "shared/stripe_checkout_button" %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>


<%= render 'new_comment' %>
<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
<%= render 'comments' %>
<%= will_paginate @comments %>