config/routes.rb
Rails.application.routes.draw do
  get 'payments/index'
  post 'payments/create'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  root 'simple_pages#landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<% if alert %>
  <p id="alert"><%= alert %></p>
<% end %>

<html>
  <head>
    <title>BySam</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative|Sacramento" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group" class="btn-group btn-group-lg" role="group">
          <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
            <%= form.label :q, 'Search for:' %>
            <%= form.text_field :q, id: 'q', value: params[:q] %>
            <%= form.submit 'Search' %>
          <% end %>
          </div>
        </form>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <p><%= link_to "Home", simple_pages_landing_page_path %> </p>
            <p><%= link_to "Products", products_path %> </p>
            <p><%= link_to "About", simple_pages_about_path %> </p>
            <p><%= link_to "Contact", simple_pages_contact_path %> </p>
          </ul>
          <ul class="navbar-nav ml auto" id="log">
            <% if user_signed_in?%>
            <li class="nav-item">
              <%= link_to('Logout', destroy_user_session_path, method: :delete,
                class: "nav-link")%>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path, class:"nav-link")%>
            </li>
            <% end %>
            </li>
          </ul>
        </div> <!--collapse-->
      </div> <!--container fluid-->
    </nav>

<%= yield %>

<footer>
  <div class="container">
     <p class="text-muted">&copy; 2018 Jewelry by Sam</p>

   </div>
</footer>

  </body>
</html>